##### Type casting

The input should be cast to `float64`.

In [4]:
import numpy as np
from sklearn import random_projection

rannge = np.random.RandomState(0)
X = rannge.rand(10,2000)
X = np.array(X, dtype = 'float32')
X.dtype

dtype('float32')

In [5]:
transformer_data = random_projection.GaussianRandomProjection()
X_new = transformer_data.fit_transform(X)
X_new.dtype

dtype('float32')

Note: in previous versions
> Unless otherwise specified, input will be cast to float64

In newer versions
> The dtype is preserved by fit and fit_transform and the main fitted attributes use a dtype of the same precision as the training data.

##### Refitting & Updating Parameters

Hyper-parameters of an estimator can be updated and refitted after it has been constructed

In [10]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.svm import SVC

X, y = load_iris(return_X_y = True)
clf = SVC()
clf.set_params(kernel = 'linear').fit(X, y)
clf.predict(X[:5])

array([0, 0, 0, 0, 0])

In [7]:
clf.set_params(kernel = 'rbf', gamma = 'scale').fit(X, y)
clf.predict(X[:5])

array([0, 0, 0, 0, 0])

##### Multiclass & Multilabel fitting

In [ ]:
from sklearn.svm import SVC
from sklearn.multiclass import OneVsRestClassifier

X = [[1, 2], [3, 4], [4, 5], [5, 2], [1, 1]]
y = [0, 0, 1, 1, 2]
classif = OneVsRestClassifier(estimator = SVC(gamma = 'scale',random_state = 0))
classif.fit(X, y).predict(X)

array([0, 1, 1, 1, 2])

It is also possible to fit upon a two-dimensional array of binary label indicators

In [9]:
from sklearn.preprocessing import LabelBinarizer

y = LabelBinarizer().fit_transform(y)
classif.fit(X, y).predict(X)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 0]])

Similarly, in case of multilabel fitting, an instance can be assigned multiple labels

In [15]:
from sklearn.preprocessing import MultiLabelBinarizer

y = [[0, 1], [0, 2], [1, 3], [0, 2], [2, 4]]
y = MultiLabelBinarizer().fit_transform(y)
# classif.fit(X, y).predict(X) # does not work with MultiLabelBinarizer